name: Terraform CI/CD

on:
  push:
    branches: [ staging, prod ]

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Prod Only)
        if: github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve

